# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csb6t2dQ9yPqAnb1reWtI4mt5mzKFODa
"""

!pip install flask-ngrok

import pandas as pd
from flask-ngrok import run_with_ngrok
from flask import Flask, request, jsonify
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

d= {"nome": "Raffael", "surname": "will", "idade": 22}

@app.route("/")
def hello():
  return "<h1>Hello World</h1>"

@app.route("/input")
def teste():
  return jsonify(d)

@app.route('/output', methods=['GET', 'POST'])

def predJson():
  pred = r.choice(["positive", "negative"])
  nd = d
  nd["pred"] = pred
  return jsonify(nd)

  app.run()